### ISSUE TITLE
java.lang.IllegalArgumentException: URI is not hierarchical 	at java.io.File.<init>(File.java:418)

### ISSUE THREAD

**Issue by sivareddyuppathi** [mfatihercik/dsm#12] opened 2020-02-15 07:39 UTC
Hi.....

I got the same error even i added **new File("")** in **DSMBuilder** 

this is my sample code 

```
DSMBuilder builder = new DSMBuilder(new File("dsm-config-file.yaml"));
DSM dsm = builder.setType(DSMBuilder.XML).create();
Pet pet = dsm.toObject(new File("path/to/xmlFile.xml"),Pet.class);
```

i try to solve my problem by using below question.....

**java.lang.IllegalArgumentException: URI is not hierarchical..**

but i codn't figure out the problem please help me..

if you want i will share my code ...

**Comment by mfatihercik** [comment] 2020-02-15 08:54
İf you write absolute path to "dsm-config-file.yaml" it will work. Problem is not related to DSM.  Java can't find the file. if the file is in your class path you should use getResourceasStrram function. 

Please check #11 issue. You can find example usage getResourceasStrram.  İf problem isn't solved please let me know.

**Comment by sivareddyuppathi** [comment] 2020-02-17 10:10
Thanks for quick response .....

i wrote absolute path to builder. builder object is created 

when i am trying to create dsm object i am getting the error

here is my code..

```
DSMBuilder builder = new DSMBuilder(new File("C:\\Users\\SivireddyUppathi\\Downloads\\split_1580192862146\\dsmYML.yml"));
DSM dsm = builder.setType(DSMBuilder.TYPE.XML).create();
Pet pet = (Pet) dsm.toObject(new File("C:\\Users\\SivireddyUppathi\\Downloads\\split_1580192862146\\dsmXML.xml"));
```

error in second line...

**Comment by mfatihercik** [comment] 2020-02-17 10:27
can you please write the error you get.

**Comment by sivareddyuppathi** [comment] 2020-02-17 10:41
run:
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.addRootPath(FileSystemResourceAccessor.java:54)
	at com.github.mfatihercik.dsb.resource.AbstractResourceAccessor.init(AbstractResourceAccessor.java:39)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.init(FileSystemResourceAccessor.java:47)
	at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.<init>(FileSystemResourceAccessor.java:27)
	at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.setResourceAccessor(AbstractConfigLoader.java:89)
	at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.<init>(AbstractConfigLoader.java:32)
	at com.github.mfatihercik.dsb.configloader.YamlConfigLoaderStrategy.<init>(YamlConfigLoaderStrategy.java:11)
	at com.github.mfatihercik.dsb.DSMBuilder.create(DSMBuilder.java:99)
	at com.ads.ammdatatypes.vo.DSMStAX.main(DSMStAX.java:38)
C:\Users\SivireddyUppathi\AppData\Local\NetBeans\Cache\11.0\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\SivireddyUppathi\AppData\Local\NetBeans\Cache\11.0\executor-snippets\run.xml:94: Java returned: 1
BUILD FAILED (total time: 1 second)

**Comment by mfatihercik** [comment] 2020-02-17 12:20
When you pass File object to DSM.toObject, DSM assume file is in classpath if you didn't specified rootPath. 
I suggest you to pass InputStream to toObject method.  You can create InputStream from File.

**Comment by sivareddyuppathi** [comment] 2020-02-17 12:49
```
        File ymlFile = new File("C:\\Users\\SivireddyUppathi\\Downloads\\split_1580192862146\\dsmYML.yml");
        InputStream ymlStream = new FileInputStream(ymlFile);
        DSMBuilder builder = new DSMBuilder(ymlStream);
        DSM dsm = builder.setType(DSMBuilder.TYPE.XML).create();
        File xmlFile = new File("C:\\Users\\SivireddyUppathi\\Downloads\\split_1580192862146\\dsmXML.xml");
        InputStream xmlStream = new FileInputStream(xmlFile);
        Pet pet = (Pet) dsm.toObject(xmlStream);
```

this is also not working for me....

for me the exception raised at below line not at toObject method...

`DSM dsm = builder.setType(DSMBuilder.TYPE.XML).create();`

**Comment by mfatihercik** [comment] 2020-02-17 13:13
Only change toObject method to use input Stream.  
Can you share exception trace

**Comment by sivareddyuppathi** [comment] 2020-02-17 17:13
Exception in thread "main" java.lang.IllegalArgumentException: URI is not hierarchical
at java.io.File.(File.java:418)
at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.addRootPath(FileSystemResourceAccessor.java:54)
at com.github.mfatihercik.dsb.resource.AbstractResourceAccessor.init(AbstractResourceAccessor.java:39)
at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.init(FileSystemResourceAccessor.java:47)
at com.github.mfatihercik.dsb.resource.FileSystemResourceAccessor.(FileSystemResourceAccessor.java:27)
at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.setResourceAccessor(AbstractConfigLoader.java:89)
at com.github.mfatihercik.dsb.configloader.AbstractConfigLoader.(AbstractConfigLoader.java:32)
at com.github.mfatihercik.dsb.configloader.YamlConfigLoaderStrategy.(YamlConfigLoaderStrategy.java:11)
at com.github.mfatihercik.dsb.DSMBuilder.create(DSMBuilder.java:99)
at com.ads.ammdatatypes.vo.DSMStAX.main(DSMStAX.java:38)
C:\Users\SivireddyUppathi\AppData\Local\NetBeans\Cache\11.0\executor-snippets\run.xml:111: The following error occurred while executing this line:
C:\Users\SivireddyUppathi\AppData\Local\NetBeans\Cache\11.0\executor-snippets\run.xml:94: Java returned: 1

**Comment by sivareddyuppathi** [comment] 2020-02-18 07:10
> Only change toObject method to use input Stream.
> Can you share exception trace

first

**Comment by mfatihercik** [comment] 2020-02-19 07:47
The problem is not related the code. which java version are you using?

**Comment by mfatihercik** [comment] 2020-02-19 16:19
#9 close this

**Closed as completed by mfatihercik** 2020-02-19 16:19 UTC

**Comment by sivareddyuppathi** [comment] 2020-02-20 05:19
Jdk 8

**Comment by mfatihercik** [comment] 2020-03-03 10:53
1.0.4 released. can you try new version.
